//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VASRDatabaseEntities : DbContext
    {
        public VASRDatabaseEntities()
            : base("name=VASRDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblCLVBWeeklyInspection> tblCLVBWeeklyInspections { get; set; }
        public virtual DbSet<tblDailyInspection> tblDailyInspections { get; set; }
        public virtual DbSet<tblDailyInspectionUpload> tblDailyInspectionUploads { get; set; }
        public virtual DbSet<tblDeptManagerSection> tblDeptManagerSections { get; set; }
        public virtual DbSet<tblDispatchLog> tblDispatchLogs { get; set; }
        public virtual DbSet<tblUsageRecord> tblUsageRecords { get; set; }
        public virtual DbSet<tblVehicleAccident> tblVehicleAccidents { get; set; }
        public virtual DbSet<tblVehicleCode> tblVehicleCodes { get; set; }
        public virtual DbSet<tblVehicleFleet> tblVehicleFleets { get; set; }
        public virtual DbSet<tblVehicleOperator> tblVehicleOperators { get; set; }
        public virtual DbSet<tblVehiclePhoto> tblVehiclePhotos { get; set; }
        public virtual DbSet<tblWeeklyDispatchLog> tblWeeklyDispatchLogs { get; set; }
        public virtual DbSet<tblWeeklyInspection> tblWeeklyInspections { get; set; }
        public virtual DbSet<viewDispatchProfile> viewDispatchProfiles { get; set; }
        public virtual DbSet<viewInspection> viewInspections { get; set; }
        public virtual DbSet<viewOperatorVehicleUsage> viewOperatorVehicleUsages { get; set; }
        public virtual DbSet<viewVehicleInspectionRecord> viewVehicleInspectionRecords { get; set; }
        public virtual DbSet<viewVehicleUsageRecord> viewVehicleUsageRecords { get; set; }
    
        public virtual ObjectResult<spExportToExcel_Result> spExportToExcel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spExportToExcel_Result>("spExportToExcel");
        }
    
        public virtual ObjectResult<spExportToExcelOperator_Result> spExportToExcelOperator()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spExportToExcelOperator_Result>("spExportToExcelOperator");
        }
    
        public virtual ObjectResult<spFilterDailyDispatch_Result> spFilterDailyDispatch(Nullable<System.DateTime> dateFilter)
        {
            var dateFilterParameter = dateFilter.HasValue ?
                new ObjectParameter("DateFilter", dateFilter) :
                new ObjectParameter("DateFilter", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFilterDailyDispatch_Result>("spFilterDailyDispatch", dateFilterParameter);
        }
    
        public virtual ObjectResult<spFilterDailyInspection_Result> spFilterDailyInspection(Nullable<System.DateTime> dateFilter)
        {
            var dateFilterParameter = dateFilter.HasValue ?
                new ObjectParameter("DateFilter", dateFilter) :
                new ObjectParameter("DateFilter", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFilterDailyInspection_Result>("spFilterDailyInspection", dateFilterParameter);
        }
    }
}
